# Generated by Django 2.1.4 on 2018-12-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restuarants',
            name='PlaceCode',
        ),
        migrations.DeleteModel(
            name='restuarants',
        ),
    ]
