# Generated by Django 2.1.4 on 2018-12-28 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0002_auto_20181228_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='restuarants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restPic', models.ImageField(upload_to='images/')),
                ('restName', models.CharField(max_length=50)),
                ('rating', models.FloatField(max_length=10)),
                ('PlaceCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restuarant.place')),
            ],
        ),
    ]
