# Generated by Django 2.1.5 on 2019-01-14 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0003_restuarants'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menupic', models.ImageField(upload_to='images/')),
                ('menuName', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('rating', models.FloatField(max_length=50)),
                ('restcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restuarant.restuarants')),
            ],
        ),
    ]
